# Generated by Django 5.1.3 on 2025-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloworld", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(default="user", max_length=6),
        ),
    ]
