# Generated by Django 5.1.3 on 2025-04-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloworld", "0002_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("user_upload", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("with_helmet", models.CharField(max_length=30)),
                ("without_helmet", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "Record",
            },
        ),
    ]
