# Generated by Django 5.1.3 on 2025-04-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloworld", "0003_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="created_at",
            field=models.CharField(max_length=60),
        ),
    ]
